server:
  port: 8081

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/staff_db
    username: root
    password: Niraj7481+-@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


