server:
  port: 8083

spring:
  application:
    name: guest-service
  datasource:
    url: jdbc:mysql://localhost:3306/guest_db
    username: root
    password: Niraj7481+-@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/